CUTOFF_FREQ: 0.1
SAMPLE_RATE: 100

WINDOW_SIZE: 100
STEP_SIZE: 50

API_KEY: patMswkrKzfHWSG3U.a882cccc6e7709b3a24b42b7f9c0ccd48ed15614f13c54e4d3dbaa55ba8ffffb
BASE_ID: appaCiWbsAFmlkOLF
TABLE_NAME: tblZtbDVHfCaoTnsH
BASE_URL: https://api.airtable.com/v0/

MIN_REPS: 1

DATA_COLUMNS:
  - AccX
  - AccY
  - AccZ
  - VelX
  - VelY
  - VelZ
  - PosX
  - PosY
  - PosZ
  - Pitch
  - Roll
  - Yaw

EXERCISE_TYPES:
  - Ab Rollout
  - Bench
  - DB Bench
  - DB Bicep Curl
  - DB Deadlift
  - DB Goblet Squat
  - DB Side Raise
  - Deadlift
  - Front Squat
  - Horizontal Chest Press
  - Lat Pulldown
  - OHP
  - Row
  - Seated Cable Rows
  - Squat
  - Tricep Cable Pushdown